import type { Candidate } from './types'

/**
 * Example candidates spanning all 6 `CandidateStatus` values so every
 * Admisión screen has realistic data to render against from the start.
 * Mirrors this codebase's existing hardcoded-example-array pattern (see
 * `pages/DivisionesList.tsx`'s `rows` const).
 */
export const mockCandidates: Candidate[] = [
  {
    id: '1',
    folio: 'ADM-2026-000101',
    nombre: 'Ana Torres Medina',
    curp: 'TOMA050312MDFRRN08',
    email: 'ana.torres@example.com',
    telefono: '777 123 4501',
    programa: 'Ingeniería en Desarrollo y Gestión de Software',
    division: 'División de Tecnologías de la Información',
    canal: 'Redes Sociales',
    status: 'REGISTERED',
    fechaRegistro: '02/06/2026',
    examen: null,
    induccionResultado: null,
    induccionHabilitada: false,
    pagoFicha: { status: 'PENDIENTE', monto: 500 },
    pagoInduccion: { status: 'PENDIENTE', monto: 350 },
  },
  {
    id: '2',
    folio: 'ADM-2026-000102',
    nombre: 'Luis Fernández Osorio',
    curp: 'FEOL040822HMSRRS03',
    email: 'luis.fernandez@example.com',
    telefono: '777 123 4502',
    programa: 'Licenciatura en Administración',
    division: 'División de Ciencias Económico Administrativas',
    canal: 'Feria Universitaria',
    status: 'REGISTERED',
    fechaRegistro: '05/06/2026',
    examen: null,
    induccionResultado: null,
    induccionHabilitada: false,
    pagoFicha: { status: 'PENDIENTE', monto: 500 },
    pagoInduccion: { status: 'PENDIENTE', monto: 350 },
  },
  {
    id: '3',
    folio: 'ADM-2026-000103',
    nombre: 'María Ramírez Cordero',
    curp: 'RACM040915MDFMRR07',
    email: 'maria.ramirez@example.com',
    telefono: '777 123 4503',
    programa: 'Ingeniería Industrial',
    division: 'División de Ingeniería',
    canal: 'Sitio Web',
    status: 'PAID',
    fechaRegistro: '28/05/2026',
    examen: null,
    induccionResultado: null,
    induccionHabilitada: false,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88213', metodo: 'Ventanilla', fecha: '30/05/2026' },
    pagoInduccion: { status: 'PENDIENTE', monto: 350 },
  },
  {
    id: '4',
    folio: 'ADM-2026-000104',
    nombre: 'Jorge Salinas Vega',
    curp: 'SAVJ040701HMSLGR09',
    email: 'jorge.salinas@example.com',
    telefono: '777 123 4504',
    programa: 'Ingeniería en Desarrollo y Gestión de Software',
    division: 'División de Tecnologías de la Información',
    canal: 'Referido',
    status: 'EXAM_TAKEN',
    fechaRegistro: '20/05/2026',
    examen: { fecha: '10/06/2026', calificacion: 82 },
    induccionResultado: null,
    induccionHabilitada: true,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88214', metodo: 'Evo Payments', fecha: '22/05/2026' },
    pagoInduccion: { status: 'CONFIRMADO', monto: 350, referencia: 'REF-91002', metodo: 'Evo Payments', fecha: '01/06/2026' },
  },
  {
    id: '5',
    folio: 'ADM-2026-000105',
    nombre: 'Carla Domínguez Ibarra',
    curp: 'DOIC040203MDFMBR02',
    email: 'carla.dominguez@example.com',
    telefono: '777 123 4505',
    programa: 'Licenciatura en Administración',
    division: 'División de Ciencias Económico Administrativas',
    canal: 'Redes Sociales',
    status: 'EXAM_TAKEN',
    fechaRegistro: '18/05/2026',
    examen: { fecha: '09/06/2026', calificacion: 45 },
    induccionResultado: null,
    induccionHabilitada: false,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88215', metodo: 'Ventanilla', fecha: '19/05/2026' },
    pagoInduccion: { status: 'PENDIENTE', monto: 350 },
  },
  {
    id: '6',
    folio: 'ADM-2026-000106',
    nombre: 'Diego Herrera Campos',
    curp: 'HECD040611HMSRRG05',
    email: 'diego.herrera@example.com',
    telefono: '777 123 4506',
    programa: 'Ingeniería en Desarrollo y Gestión de Software',
    division: 'División de Tecnologías de la Información',
    canal: 'Sitio Web',
    status: 'ACCEPTED',
    fechaRegistro: '10/05/2026',
    examen: { fecha: '05/06/2026', calificacion: 90 },
    induccionResultado: { fecha: '12/06/2026', resultado: 'Asistió' },
    induccionHabilitada: true,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88216', metodo: 'Evo Payments', fecha: '11/05/2026' },
    pagoInduccion: { status: 'CONFIRMADO', monto: 350, referencia: 'REF-91003', metodo: 'Evo Payments', fecha: '15/05/2026' },
  },
  {
    id: '7',
    folio: 'ADM-2026-000107',
    nombre: 'Patricia Núñez Ávila',
    curp: 'NUAP040428MDFXVT06',
    email: 'patricia.nunez@example.com',
    telefono: '777 123 4507',
    programa: 'Ingeniería Industrial',
    division: 'División de Ingeniería',
    canal: 'Feria Universitaria',
    status: 'REJECTED',
    fechaRegistro: '08/05/2026',
    examen: { fecha: '04/06/2026', calificacion: 40 },
    induccionResultado: null,
    induccionHabilitada: false,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88217', metodo: 'Ventanilla', fecha: '09/05/2026' },
    pagoInduccion: { status: 'PENDIENTE', monto: 350 },
  },
  {
    id: '8',
    folio: 'ADM-2026-000108',
    nombre: 'Sofía Martínez Roldán',
    curp: 'MARS040119MDFRLF01',
    email: 'sofia.martinez@example.com',
    telefono: '777 123 4508',
    programa: 'Licenciatura en Administración',
    division: 'División de Ciencias Económico Administrativas',
    canal: 'Referido',
    status: 'ENROLLED',
    fechaRegistro: '02/05/2026',
    examen: { fecha: '28/05/2026', calificacion: 95 },
    induccionResultado: { fecha: '03/06/2026', resultado: 'Asistió' },
    induccionHabilitada: true,
    pagoFicha: { status: 'CONFIRMADO', monto: 500, referencia: 'REF-88218', metodo: 'Evo Payments', fecha: '03/05/2026' },
    pagoInduccion: { status: 'CONFIRMADO', monto: 350, referencia: 'REF-91004', metodo: 'Evo Payments', fecha: '06/05/2026' },
    matricula: '2026LADM0087',
  },
  {
    id: '9',
    folio: 'ADM-2026-000109',
    nombre: 'Emiliano Castro Uribe',
    curp: 'CAUE040527HMSSRR04',
    email: 'emiliano.castro@example.com',
    telefono: '777 123 4509',
    programa: 'Ingeniería en Desarrollo y Gestión de Software',
    division: 'División de Tecnologías de la Información',
    canal: 'Sitio Web',
    status: 'ACCEPTED',
    fechaRegistro: '01/05/2026',
    examen: { fecha: '25/05/2026', calificacion: 100 },
    induccionResultado: { fecha: '30/05/2026', resultado: 'Asistió' },
    induccionHabilitada: true,
    pagoFicha: { status: 'EXENTO', monto: 0, montoOriginal: 500, referencia: 'DESC-100', metodo: 'Descuento 100%', fecha: '01/05/2026' },
    pagoInduccion: { status: 'EXENTO', monto: 0, montoOriginal: 350, referencia: 'DESC-100', metodo: 'Descuento 100%', fecha: '01/05/2026' },
  },
]
